### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by christiams** [digisfera/lr-http-server#3]
I installed all dependencies and when i execute command "lr-http-server" console return white ... i don't know what i missing.. Finally return "node_modules\lr-http-server\node_modules\gaze\lib\gaze.js:331 return this._handleError(err);RangeError: Maximum call stack size exceeded"

**Comment by manuelcabral** [comment]
Are you still having this issue? The gaze version has been updated recently.
