### ISSUE TITLE
Ability to open some url

### ISSUE THREAD

**Issue by adavidof** [digisfera/lr-http-server#4]
Hello @manuelcabral :)

It will be a good if you add the ability to add some url to opening exist url when open the page, for example:
`lr-http-server -d min/ -u index.html/#/main`

And the server will open my server with url:
`min/index.html/#/main`

The `u` flag can set the url

Best regards!

**Comment by adavidof** [comment]
@manuelcabral
I did the changes and pull-request but I can't push the branch to remote

**Comment by manuelcabral** [comment]
Closed by #7 . Thanks for the PR!
