### ISSUE TITLE
Adding new files after server launch are not detected by gaze

### ISSUE THREAD

**Issue by pflannery** [digisfera/lr-http-server#5]
This is because it's watching files using absolute paths. [At this line](https://github.com/digisfera/lr-http-server/blob/master/src/index.js#L54) 

The fix for this would be to gaze at the relative paths instead.

```js
    gaze(watchFiles, function(err, watcher) {
      if(err) {
        console.error("Unable to watch files", err);
      }
      this.on('all', function(event, filepath) {
        console.log(filepath + ' was ' + event);
        livereloadServer.changed({body:{files:filepath}});
      });
    });
```

@manuelcabral I can PR this.

**Comment by manuelcabral** [comment]
Thanks, please do.

For reference, some corresponding gaze issues are [#84](https://github.com/shama/gaze/issues/84) and [#80](https://github.com/shama/gaze/issues/80).
